name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.3'  # Specify the Node.js version you need

      # Step 3: Install dependencies in the 'website' directory
      - name: Install dependencies
        working-directory: ./my-react-app
        run: npm install

      # Step 4: Build the React application
      - name: Build React app
        working-directory: ./my-react-app
        run: npm run build

      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 6: Deploy the build to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./my-react-app/build s3://${{ secrets.S3_BUCKET }} --delete
